### ISSUE TITLE
Consider whether we're missing internally-linked content

### ISSUE THREAD

**Issue by wisniewskit** [webcompat/testcase-reducer#1]
I suspect that we're pruning SVG defines and the like, when they are not auspiciously in the sub-tree we're considering. I also suspect we may be missing `style` and `link` tags that are defined in the `body`, rather than the `head`.

STR likely demonstrating the SVG issue:
1. https://hatchboxnz.com/
2. focus the div with `class="gallery"` in inspector
3. activate testcase reducer
4. tick boxes for Include Ancestor Nodes and Include @media rules
5. click reduce

**Comment by dione2** [comment]
Thanks

**Comment by wisniewskit** [comment]
There are multiple issues to fix here:
1. We aren't fully-qualifying URLs in <style> tags relative to the stylesheet's URL, but the document's. This makes the reduced test-case link to the wrong background images, leading to the dark background.
2. Links to the internal document are erroneously fully-qualified, which causes clip-paths to break.
3. We aren't handling <use> elements properly, or copying over references from <def> elements elsewhere in the document tree compared to the subtree we're considering (including clip-path type internal references from CSS).
4. We aren't filtering out <link> elements for stylesheets from the subtree, despite not needing them (which we don't actually want to do).

**Comment by wisniewskit** [comment]
I've corrected the above, but there is still something left which is causing the precise STR to fail (yet if I select an ancestor of the `.gallery` node (`.ajax-content-wrap`) then things are working with my fixes). I'll investigate the remaining breakage when I can.

**Comment by wisniewskit** [comment]
Actually, the breakage is happening because there are spacer sibling elements around `.gallery`'s ancestor node `.ajax-content-wrap`, which are needed for the layout to work. So I don't actually think this is a flaw in the addon, so much as reducing the test-case requires including those elements (or equivalent space). I'm not sure if there is a realistic way for the addon to guess at such things, so I think it's up to the user to just select parent nodes and clicking `reduce` until a workable starting point is found.
